export { default as activeIcon } from './active-icon.svg';
export { default as activity1} from './activity1.png';
export { default as addPic2 } from './add-pic2.svg';
export { default as addPic3 } from './add-pic3.svg';
export { default as comicIcon } from './comic.svg';
export { default as film1} from './film1.png';
export { default as film2} from './film2.png';
export { default as filmIcon } from './film.svg';
export { default as fingureIcon } from './fingure.svg';
export { default as game1} from './game1.png';
export { default as gameBoyBlue } from './game-boy-blue.png';
export { default as gameBoyRed } from './game-boy-red.png';
export { default as gameIcon } from './gameIcon.svg';
export { default as comic1} from './comic1.png';
export { default as comic2} from './comic2.png';
export { default as comic3} from './comic3.png';
